# Generated by Django 2.0.5 on 2018-05-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180513_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_date',
        ),
    ]
