# Generated by Django 2.0.5 on 2018-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20180505_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
