# Generated by Django 2.0.5 on 2018-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20180511_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(null=True, to='twitter.Tag'),
        ),
    ]
