# Generated by Django 2.0.5 on 2018-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20180511_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='twitter.Tag'),
        ),
    ]
