# Generated by Django 2.0.5 on 2018-05-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20180512_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='score',
        ),
    ]
